name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use the environment secret
        run: echo ${{ secrets.VPS_HOST }}
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /home/nextjs-large-file-upload
            git pull origin main
            pnpm clean-install
            pnpm run build
            pm2 start
            pm2 ls
            pm2 logs large-file-upload --nostream
