name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 8.15.0
      - run: pnpm install --frozen-lockfile
      - run: pnpm test -- --run
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 8.15.0
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
  deploy:
    env:
      repo: https://github.com/${{ github.repository }}
      branch: main
      dir: /home/nextjs-large-file-upload
    runs-on: ubuntu-latest
    steps:
      - name: Use the environment secret
        run: echo ${{ secrets.VPS_HOST }}
      - name: Use the default environment variables
        run: echo ${{ env.branch }} ${{ env.repo }} ${{ env.dir }}
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            mkdir -p ${{ env.dir }}
            cd ${{ env.dir }}
            git init
            git remote add origin ${{ env.repo }}
            git fetch --all
            git reset --hard origin/${{ env.branch }}
            pnpm install --frozen-lockfile
            pnpm run build
            pm2 start
            pm2 ls
            pm2 logs --nostream
